### PR TITLE
Sort & report all cached matches

### LINKED ISSUE #13: Return all cached results
After #12 chat command returns records from cache but only first result for single player.
Multiple cached results for single player name are very much possible, better behavior would be to return all results sorted by timestamp.

Should be simple to add by storing timestamp to players table and then in chat command handler collect sort by that timestamp, allows also easily displaying player login timestamp for each IP address.

### PR DESCRIPTION
**Pull request by S-S-X**
~Bit messy and wont search for other records if player is online but only if ip isn't available.~

~So could be improved for sure, does this seem acceptable?~

Edit: Fixed it and now it does finds multiple matches also for online players and output is same no matter if player is available or not.

Might kill server or something, I've no idea... would be good to do some simple testing first.

Closes #13

### CODE REVIEW

**Comment by S-S-X** [comment]
Fixed it and now it does finds multiple matches also for online players and output is same no matter if player is available or not.
Still have not tested in game.

**Comment by S-S-X** [comment]
Added Mineunit auth module, after https://github.com/S-S-X/mineunit/pull/87 is merged Mineunit will also execute prejoin callbacks. Verified that prejoin callbacks do work with tests.

**Comment by BuckarooBanzay** [comment]
>  Still have not tested in game.

Let me know if you need help, i could spare some time to introduce this on the pandorabox-test server

**Comment by S-S-X** [comment]
> Let me know if you need help, i could spare some time to introduce this on the pandorabox-test server

Maybe I'll update docs (readme) and then yes it would be nice if we can test this on pandorabox test server.

**Comment by S-S-X** [comment]
>> Let me know if you need help, i could spare some time to introduce this on the pandorabox-test server

> Maybe I'll update docs (readme) and then yes it would be nice if we can test this on pandorabox test server.

Done:

Changes for LICENSE.txt only adds line breaks and does not change actual contents / text.
Added simple examples to documentation, prejoin callback registration and TTL configuration.
Added assertions for callback registration to fail early if registration itself is invalid.

I think this is ready for testing... and if we're lucky and it somehow works then also ready for merging.

**Comment by BuckarooBanzay** [comment]
> I think this is ready for testing... and if we're lucky and it somehow works then also ready for merging.

Added this to the test-server and it looks good so far:
Screenshot_2022-08-12_07-45-03

**Comment by S-S-X** [comment]
Looking at screenshot maybe list order should be reversed?

**Comment by S-S-X** [comment]
Didn't crash so it has to be perfect, or good enough at least... closing

**Pull request merged**
