### PR TITLE
GeoIP updates

### LINKED ISSUE #5: Few improvements
* Forward last login timestamp through `geoip.joinplayer_callback`.
    * Required
* Allow registering event handlers for `geoip.joinplayer_callback`.
    * Previous callback override style can stay around or it can be replaced, TBD?
    * Not as important and not really required, function override works too and might be better to allow cutting chain if player is removed?

This is to make upcoming [beowulf](https://github.com/mt-mods/beowulf) updates a lot simpler.

### LINKED ISSUE #6: Optional QoS support
With highest priority and low timeout (timeout is already at 1 second).

Increases QoS accuracy, even if not limiting requests having optional support gives benefits:
* Increases request prioritization accuracy for counters and utilization reports.
* Allows limiting low priority requests earlier to make space for high priority requests if queues are full.
    * Without optional QoS support low priority requests can delay any requests from mods that do not use QoS.

### PR DESCRIPTION
**Pull request by S-S-X**
Updates mod config and tests.

Update API and add event registration.

Add optional QoS support.

Closes #5 #6

### CODE REVIEW

**Comment by S-S-X** [comment]
**TBD:** Should geoip "work" without crashing if dependencies are not available (http and get_player_ip)?

Before it was checking for http availability logging error and continuing without loading mod, this would cause crash later if API is used by another mod.

For now I've changed logging to assert so it will crash early and with very clear error message, early failure should make this less confusing. Is there anything wrong with that (remember: mod does not provide anything without required dependencies and should be disabled or configured properly)?

**Comment by S-S-X** [comment]
Remember that beowulf ASN kick will break with this, I've already worked a bit to update beowulf mod (https://github.com/mt-mods/beowulf/issues/6).
Not sure if changes here can cause crashes in beowulf or if it will just disable ASN ban functionality.

**Comment by BuckarooBanzay** [comment]
> TBD: Should geoip "work" without crashing if dependencies are not available (http and get_player_ip)?

If possible, yes. IMO it should fail with a warning, so mod integration-tests/CI (like on pandorabox) can still be executed but without enabling the http api.

**Comment by S-S-X** [comment]
> If possible, yes. IMO it should fail with a warning, so mod integration-tests/CI (like on pandorabox) can still be executed but without enabling the http api.

Yes could add no-op metatable for geoip. That allows calling any function but everything returns nil / wont ever execute any callbacks (like geoip.lookup).
Should work fine, I'll add that or something like that here and remove asserts.

**Comment by S-S-X** [comment]
> If possible, yes. IMO it should fail with a warning, so mod integration-tests/CI (like on pandorabox) can still be executed but without enabling the http api.

Done in a way that when not in trusted mods you can call anything on geoip as function and it simply always returns nil.
Basically functions are defined so `geoip.register_on_joinplayer(function(a,b,c) do_stuff() end)` resgistration works but does not actually do anything.

edit. also throws warnings to log every time geoip functions are used and one error during mod loading.

**Review by BuckarooBanzay — APPROVED** [review]

**Pull request merged**
